[tool.poetry]
name = "dolt"
version = "0.1.0"
description = ""
authors = ["Andy Arthur <andy@dolthub.com>"]
license = "LICENSE.txt"

[tool.poetry.dependencies]
python = "^3.6"
nautobot = "^1.1.0"
mysqlclient = "^2.0.3"
nautobot-bgp-models = {path = "packages/nautobot_bgp_models-0.5.0-py3-none-any.whl"}


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
